export const iconTypes = {
  normal: 'https://static.wikia.nocookie.net/pyruslords/images/1/1d/Normal_Type.png',
  fighting: 'https://static.wikia.nocookie.net/pyruslords/images/c/ce/Fighting_Type.png',
  flying: 'https://static.wikia.nocookie.net/pyruslords/images/e/ec/Flying_Type.png',
  poison: 'https://static.wikia.nocookie.net/pyruslords/images/a/ad/Poison_Type.png',
  ground: 'https://static.wikia.nocookie.net/pyruslords/images/c/c4/Ground_Type.png',
  rock: 'https://static.wikia.nocookie.net/pyruslords/images/6/69/Rock_Type.png',
  bug: 'https://static.wikia.nocookie.net/pyruslords/images/0/0b/Bug_Type.png',
  ghost: 'https://static.wikia.nocookie.net/pyruslords/images/d/d3/Ghost_Type.png',
  steel: 'https://static.wikia.nocookie.net/pyruslords/images/5/5f/Steel_Type.png',
  fire: 'https://static.wikia.nocookie.net/pyruslords/images/0/0a/Fire_Type.png',
  water: 'https://static.wikia.nocookie.net/pyruslords/images/2/25/Water_Type.png',
  grass: 'https://static.wikia.nocookie.net/pyruslords/images/f/f8/Grass_Type.png',
  electric: 'https://static.wikia.nocookie.net/pyruslords/images/6/6f/Electric_Type.png',
  psychic: 'https://static.wikia.nocookie.net/pyruslords/images/0/00/Psychic_Type.png',
  ice: 'https://static.wikia.nocookie.net/pyruslords/images/5/50/Ice_Type.png',
  dragon: 'https://static.wikia.nocookie.net/pyruslords/images/2/24/Dragon_Type.png',
  dark: 'https://static.wikia.nocookie.net/pyruslords/images/5/51/Dark_Type.png',
  fairy: 'https://static.wikia.nocookie.net/pyruslords/images/0/01/Fairy_Type.png'
}
